metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

processors:
  - add_docker_metadata: ~
  - add_host_metadata: ~
  - add_cloud_metadata: ~

metricbeat.modules:
  - module: elasticsearch
    xpack.enabled: true
    period: 10s
    hosts: ${ELASTIC_HOSTS}
    ssl.certificate_authorities: "certs/ca/ca.crt"
    ssl.certificate: "certs/es01/es01.crt"
    ssl.key: "certs/es01/es01.key"
    username: ${ELASTIC_USER}
    password: ${ELASTIC_PASSWORD}
    ssl.enabled: true

  - module: logstash
    xpack.enabled: true
    period: 10s
    hosts: ${LOGSTASH_HOSTS}
  
  - module: system
    metricsets: ["cpu", "memory", "network", "process"]
    period: 10s
    processes: [".*"]
    cpu.metrics: ["percentages", "normalized_percentages"]
    core.metrics: ["percentages"]

  - module: docker
    metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

# output.logstash:
#   hosts: ["logstash01:5044"]

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl:
    certificate: "certs/es01/es01.crt"
    certificate_authorities: "certs/ca/ca.crt"
    key: "certs/es01/es01.key"
